#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  generate_collision_mesh.sh INPUT.ply OUTPUT_BASE SEED_X,SEED_Y,SEED_Z [VOXEL_SIZE]

Creates OUTPUT_BASE.clustered.ply and the splat-transform voxel/smooth-mesh
pair OUTPUT_BASE.voxel.{json,bin} + OUTPUT_BASE.collision.glb.  The voxel pair
is an intermediate generated by splat-transform; formal gs-agent scene
manifests should reference only the GLB.

Environment:
  SPLAT_TRANSFORM_NODE  Node.js executable (default: node)
  SPLAT_TRANSFORM_CLI   Absolute path to splat-transform cli.mjs (required)
  SPLAT_TRANSFORM_GPU   WebGPU adapter index (default: 0)
EOF
}

if [[ $# -lt 3 || $# -gt 4 ]]; then
  usage >&2
  exit 2
fi

input_ply=$1
output_base=$2
seed_pos=$3
voxel_size=${4:-0.06}
node_bin=${SPLAT_TRANSFORM_NODE:-node}
cli=${SPLAT_TRANSFORM_CLI:-}
gpu=${SPLAT_TRANSFORM_GPU:-0}

if [[ -z "$cli" ]]; then
  echo "SPLAT_TRANSFORM_CLI must point to splat-transform's cli.mjs" >&2
  exit 2
fi
if [[ ! -f "$input_ply" ]]; then
  echo "input PLY does not exist: $input_ply" >&2
  exit 2
fi
if [[ ! -f "$cli" ]]; then
  echo "splat-transform CLI does not exist: $cli" >&2
  exit 2
fi

mkdir -p "$(dirname "$output_base")"
clustered_ply="${output_base}.clustered.ply"
voxel_json="${output_base}.voxel.json"

echo "Filtering the connected Gaussian cluster around seed $seed_pos"
"$node_bin" "$cli" -g "$gpu" --seed-pos="$seed_pos" \
  "$input_ply" --filter-cluster "$clustered_ply"

echo "Generating ${voxel_size}-resolution smooth collision mesh"
"$node_bin" "$cli" -g "$gpu" \
  "$clustered_ply" "$voxel_json" \
  --voxel-size "$voxel_size" --collision-mesh smooth

echo "Collision mesh: ${output_base}.collision.glb"
